import os
from dotenv import load_dotenv
load_dotenv()


GITHUB_API = "https://api.github.com"

# Place `GITHUB_TOKEN=token` in your .env
TOKEN = os.environ.get('GITHUB_TOKEN')

HEADERS = {
    "Accept": "application/vnd.github+json",
    "Authorization": f"token {TOKEN}",
}

orgs = [
    'ergoplatform',
    'scorexfoundation',
    'ErgoRaffle',
    'ergo-pad',
    'ergopad',
    'skyharbor-market',
    'duckpools',
    'fleet-sdk',
    'LiliumErgo',
    'Satergo',
    'ergoMixer',
    'ergonames',
    'Ergo-Lend',
    'GetBlok-io',
    'GuapSwap',
    'Lithos-Protocol',
    'nightowlcasino',
    'paideiadao',
    'TosiDrop',
    'anetaBTC',
    'Kalita-Platform',
    'DeCo-Education',
    'learn-ergo',
    'sigmastamp',
    'ergo-index',
    'Ergohack-Dashboard-Project',
    'rosen-bridge',
    'ErgoGravity',
    'SentientFoundation',
    'spectrum-finance',
    'ergolabs',
]

users = [
    'mhssamadani',
    'anon-real',
    'kushti',
    'capt-nemo429',
    'Luivatra',
    'ergflip',
    'anon-br',
    'aslesarenko',
    'minotaur-ergo',
    'inergitance',
    'ObolFlip',
    'CometCommunity',

]

repos = [
    #'bdkent/sigmausd-history', Excluded as generates hundreds of commits
    'abchrisxyz/ergo-setup',
    'abchrisxyz/ergowatch',
    'ach2swift/ErgoStats',
    'andrehafner/ergo-payroll',
    'andrehafner/my.ergoport.dev',
    'andyceo/ergopyng',
    'ApexTheory/appkit-by-example',
    'aragogi/scanner-front',
    'aragogi/Stealth-doc',
    'azhiganov/ergo-golang',
    'babygrenade/ergo-tokenautics',
    'bdkent/ergo-status',
    'capt-nemo429/eip12-types',
    'capt-nemo429/ergo-graphql',
    'coinbarn/ergo-ts',
    'collincrypto/gambitcrypto',
    'cornbelt-dev/sigma-subscriptions-manager',
    'CryptoCream/ErgoVision',
    'crystoll/export-erg-transactions',
    'danieloravec/ergo-token-swap',
    'dav009/ergo-puppet',
    'dav009/ergo-scala-skeleton-app',
    'dav009/strainer',
    'deadit/paizo',
    'Dmdv/server-interpreter',
    'dzyphr/2pAtomicSwapExample',
    'dzyphr/atomicswapexample',
    'dzyphr/ScalaSigmaParticle',
    'dzyphr/SigmaParticle',
    'Eeysirhc/ergo-champions-bot',
    'Eeysirhc/ergo-rpi',
    'Eeysirhc/ergo_intelligence',
    'Eeysirhc/sigmabot',
    'Eeysirhc/tidyergo',
    'Emurgo/age-usd',
    'Emurgo/yoroi-ergo-backend',
    'Emurgo/yoroi-ergo-connector',
    #'ericksonwinter/boxer', 404
    'FlyingPig69/Ergo_Explorer_Queries',
    'freeboy0/ergo-token-analysis',
    'glasgowm148/ergonaut-handbook',
    #'gnuion/ergofund-frontend', 404
    'gsblabsio/azorus',
    'gsblabsio/ergo-analytics',
    'hypo10use/quid-games',
    'iandebeer/ergo-castanet',
    'ilyaLibin/dAppStep',
    'input-output-hk/scrypto',
    'jaysee260/ergo-playground',
    'jaythiya/ergodns-frontend',
    'jellymlg/ergo',
    'jellymlg/ErgoSphere',
    'johannesstrueber/ergo-nft-viewer',
    'K-9Nine/ergodao',
    'K-Singh/ergo-subpooling',
    'K-Singh/Sigma-Finance',
    'kii-dot/dumdumdum',
    'knizhnik/scorex_crypto_avltree',
    'Kolmen-Tech/ErgoPOS',
    #'koukarin/ErgoneV2-front-end', 404
    'koukarin/Local-Economy-Wallet',
    'kushti/ergo-simple-addresses',
    'kushti/kya',
    'ladopixel/ErgoNFTs',
    'ladopixel/ErgoToolsBot',
    'ladopixel/ErgoTutorials.com',
    'ladopixel/schedulERG',
    'ladopixel/schedulERGweb',
    'ladopixel/tERGminal',
    'lorien/ergotools',
    'lucagdangelo/flowcardLib',
    'Luivatra/airdropaddressrecorder',
    'Luivatra/ergotipper-tokens',
    'Luivatra/koinly-csv-extract',
    'Luivatra/oracle-core',
    'mapp0/Ergo_DE',
    'mgpai22/comet-airdrop-bot',
    'mgpai22/comet-lottery',
    'mgpai22/comet-lottery-docker',
    'mgpai22/ergo-miner-reward-consolidator',
    'mgpai22/ergo-nft-bulk-minter',
    'mgpai22/ergo-synced-node',
    'mgpai22/ergo_faucet',
    'mgpai22/ergoappkit-spent-box-explorer',
    'mgpai22/ergosapiens-payment-portal',
    'mgpai22/ergpy',
    'mgpai22/ergpy-native',
    'mgpai22/paiNet',
    'MrStahlfelge/ergo-offchain',
    'MrStahlfelge/mosaik',
    'MrStahlfelge/mosaik-ageusddemo',
    'MrStahlfelge/mosaik-tutorial-series',
    'NazeriMahdi2001/Raffle-Doc',
    'networkspore/Netnotes',
    'nirvanush/dao-dapp',
    'nirvanush/dappstep-docs',
    'nirvanush/dappstep-play',
    'nirvanush/ergoscript',
    'nirvanush/ergoscript-nodejs',
    'nirvanush/txbuilder-service',
    'nirvanush/whale-alerts-twitter-bot',
    'nn-dmt/swamp_ergo',
    #'osmanthusleaf/ergo-gig', 404
    'pragmaxim/ergo-spikechain',
    'pragmaxim/ergo-uexplorer',
    'pulsarz/sigmaexplorer',
    'reqlez/tn-ergo-easy-oracle',
    'rf-peixoto/ergopy',
    'robkorn/ergo-utilities-rust',
    'ross-weir/ergo-script-re',
    'ross-weir/ergo-stealth-address-example',
    'ross-weir/ergode',
    'ross-weir/Ergode.Bridge',
    'ross-weir/Ergode.Tizen',
    'ross-weir/just-ergo-things',
    'SabaunT/ergo-handshake',
    'SabaunT/ergo-monitoring',
    'scalahub/Kiosk',
    'scorexfoundation/scorex',
    'ScorexFoundation/sigmastate-interpreter',
    'sigmastamp/sigmastamp-frontend',
    'sininen-taivas/ergo-lets',
    'sininen-taivas/ergo-notary',
    'sininen-taivas/ergo-numerals',
    'sininen-taivas/ergo-oracle',
    'sininen-taivas/ergo-test',
    'sininen-taivas/ergo-wbo',
    'sininen-taivas/ergoutils',
    'sininen-taivas/pricing-feeds',
    'supERGeometry/Ergold',
    'tesseract-one/ledger-app-ergo',
    'thedlop/sigma_mint',
    'thedlop/sigma_rb',
    'thedlop/twotens',
    'ThierryM1212/blobs-topia',
    'ThierryM1212/cyti',
    'ThierryM1212/ergo-pay',
    'ThierryM1212/ergo-token-minter',
    'ThierryM1212/SAFEW',
    'ThierryM1212/SigmaO',
    'ThierryM1212/transaction-builder',
    'WilfordGrimley/eip38PartialVoting',
    'WilfordGrimley/ergo',
    'WilfordGrimley/ErgoSmartPools',
    'zackbalbin/ErgoTutorials',
    'zargarzadehm/ergo-faucet',
    'zkastn/ergo-raffle-bot',
    'c8e4d2a/inferno.black',
    'c8e4d2a/breedserver',
    'c8e4d2a/breedutils',    
]
